version: '3.3'

services:

  beecoin-prod:
    stdin_open: true
    container_name: beecoin-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - "./:/app"